name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "DOCKERHUB_USER is set to: ${{ secrets.DOCKERHUB_USER }}"
          echo "DOCKERHUB_TOKEN length: $(echo -n ${{ secrets.DOCKERHUB_TOKEN }} | wc -c)"
          echo "Secrets available: $(env | grep DOCKERHUB)"
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Docker Version
        run: |
          docker --version
          docker info --format '{{.ClientInfo}}'

      - name: Manual Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
        continue-on-error: true  # Allow workflow to continue even if this fails

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        continue-on-error: true  # Allow workflow to continue for debugging

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"